# ============================================================
# Project:  Intelligent Street Communication System (ISCS)
# File:     routes/summaries.py
# Author:   Dana Omar
# Last Modified: May 2026
# Author:   Batool Alkhateeb
# Last Modified: June 2026
# Purpose:  Provides API endpoints for retrieving traffic
#           summaries generated by the aggregation service.
#
#           Auth: driver, public_safety, admin (require_driver)
# ============================================================

from fastapi import APIRouter, Request, Depends
from google.cloud.firestore_v1.base_query import FieldFilter

from config import SEGMENTS_COLLECTION          # ← was hardcoded "segments" (bug fix)
from core.auth import require_driver            # ← was missing (bug fix)
from models.user_model import AuthenticatedUser

router = APIRouter(
    prefix="/summaries",
    tags=["summaries"],
)


# ─── GET /summaries ────────────────────────────────────────
# Returns the latest traffic summaries across all segments.
# Auth: driver, public_safety, admin

@router.get("/")
async def get_summaries(
    request: Request,
    user: AuthenticatedUser = Depends(require_driver),
):
    docs = (
        request.state.db.collection(SEGMENTS_COLLECTION)
        .order_by("computed_at", direction="DESCENDING")
        .limit(20)
        .stream()
    )
    summaries = [doc.to_dict() for doc in docs]
    return {
        "success":   True,
        "count":     len(summaries),
        "summaries": summaries,
    }


# ─── GET /summaries/{segment} ──────────────────────────────
# Returns traffic summaries for a specific road segment.
# Auth: driver, public_safety, admin

@router.get("/{segment}")
async def get_summaries_by_segment(
    segment: str,
    request: Request,
    user: AuthenticatedUser = Depends(require_driver),
):
    docs = (
        request.state.db.collection(SEGMENTS_COLLECTION)
        .where(filter=FieldFilter("segment", "==", segment))
        .order_by("computed_at", direction="DESCENDING")
        .limit(10)
        .stream()
    )
    summaries = [doc.to_dict() for doc in docs]
    return {
        "success":   True,
        "segment":   segment,
        "count":     len(summaries),
        "summaries": summaries,
    }
