# ============================================================
# Project:  Intelligent Street Communication System (ISCS)
# File:     routes/summaries.py
# Author:   Dana Omar
# Date:     May 2026
# Purpose:  Provides API endpoints for retrieving
#           traffic summaries generated by the
#           aggregation service.
# ============================================================

from fastapi import APIRouter, Request

router = APIRouter(
    prefix="/summaries",
    tags=["summaries"]
)


# ─── GET /summaries ────────────────────────────────────────
# Returns the latest traffic summaries across all segments.

@router.get("/")
async def get_summaries(request: Request):

    docs = (
        request.state.db.collection("segments")
        .order_by("computed_at", direction="DESCENDING")
        .limit(20)
        .stream()
    )

    summaries = [doc.to_dict() for doc in docs]

    return {
        "success": True,
        "count": len(summaries),
        "summaries": summaries,
    }


# ─── GET /summaries/{segment} ──────────────────────────────
# Returns traffic summaries for a specific road segment.

@router.get("/{segment}")
async def get_summaries_by_segment(
    segment: str,
    request: Request
):

    docs = (
        request.state.db.collection("segments")
        .where("segment", "==", segment)
        .order_by("computed_at", direction="DESCENDING")
        .limit(10)
        .stream()
    )

    summaries = [doc.to_dict() for doc in docs]

    return {
        "success": True,
        "segment": segment,
        "count": len(summaries),
        "summaries": summaries,
    }
