# ============================================================
# Project:  Intelligent Street Communication System (ISCS)
# File:     models/signal_model.py
# Author:   Raghad Shatnawi
# Date:     March 2026
# Purpose:  Defines the data structures used by the server.
#           RSUSignal              — incoming signal from an RSU
#           SignalInDB             — signal as stored in Firestore
#           SegmentTrafficSummary  — aggregated traffic snapshot per segment
#           TrafficAlert           — alert generated by the server
# ============================================================

from pydantic import BaseModel, Field
from typing import Optional, Literal
from datetime import datetime
import uuid


# ─── RSUSignal ───────────────────────────────────────────────
# Represents one signal sent by an RSU.
# Every POST request to /ingest must match this structure.
#
# Example of a valid incoming JSON:
# {
#   "event_id":      "12345",
#   "rsu_id":        "RSU_01",
#   "segment":       "Petra St",
#   "timestamp":     "2026-03-13T12:45:30",
#   "speed":         42.0,
#   "direction":     "Northbound",
#   "vehicle_count": 3
# }

class RSUSignal(BaseModel):

    # ─── REQUIRED FIELDS ────────────────────────────────────
    rsu_id:        str   = Field(..., description="ID of the RSU that sent this signal")
    segment:       str   = Field(..., description="Road segment name e.g. Petra St")
    speed:         float = Field(..., description="Average vehicle speed in km/h", ge=0)
    vehicle_count: int   = Field(..., description="Number of vehicles detected", ge=0)

    # ─── OPTIONAL FIELDS ────────────────────────────────────
    event_id:  Optional[str]      = Field(None,      description="Unique event ID from RSU")
    timestamp: Optional[datetime] = Field(None,      description="Time of detection from RSU")
    direction: Optional[str]      = Field("Unknown", description="Direction of travel")


# ─── SignalInDB ──────────────────────────────────────────────
# Extends RSUSignal with the server-side received_at timestamp.
# This is what gets saved to Firestore.

class SignalInDB(RSUSignal):

    received_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp of when the server received this signal"
    )


# ─── to_dict() ──────────────────────────────────────────────
# Converts a SignalInDB to a plain dictionary for Firestore.

def to_dict(signal: SignalInDB) -> dict:
    return {
        "event_id":      signal.event_id,
        "rsu_id":        signal.rsu_id,
        "segment":       signal.segment,
        "timestamp":     signal.timestamp.isoformat() if signal.timestamp else None,
        "speed":         signal.speed,
        "direction":     signal.direction,
        "vehicle_count": signal.vehicle_count,
        "received_at":   signal.received_at.isoformat(),
    }


# ─── TrafficState ────────────────────────────────────────────
# The classified traffic condition for a segment summary.
# Matches the Traffic State field in Table 3 of the GP1 report.
# Also used by TrafficAlert to describe the condition at alert time.

TrafficState = Literal["free", "moderate", "congested", "severe"]


# ─── SegmentTrafficSummary ───────────────────────────────────
# Represents an aggregated traffic snapshot for one road segment.
# Computed by the server during analysis and saved to the
# segments collection in Firestore.
# Matches Table 3 (SegmentTrafficSummary Data Fields) from the GP1 report.
#
# STUB STATUS:
#   Implemented now   — segment, traffic_state, vehicle_count,
#                       avg_speed, signal_count, summary_id, computed_at
#   Stubbed (None)    — window_start, window_end, flow_rate, density_proxy
#
#   window_start / window_end:
#     Requires time-window aggregation logic (60-second windows).
#     Currently set to None. Will be populated when the windowed
#     aggregation pipeline replaces the current last-10-signals approach.
#
#   flow_rate:
#     Vehicles per unit time within the window.
#     Requires a fixed window duration to calculate correctly.
#     Formula: flow_rate = vehicle_count / window_duration_seconds
#
#   density_proxy:
#     Vehicles per unit distance.
#     Formula: density_proxy = vehicle_count / segment_length_km
#     Requires segment length metadata (not yet stored in the system).
#     Will be added when a segments metadata collection is introduced.
#
# Example document in Firestore:
# {
#   "summary_id":     "uuid",
#   "segment":        "Petra St",
#   "traffic_state":  "congested",
#   "avg_speed":      32.5,
#   "vehicle_count":  42,
#   "signal_count":   10,
#   "flow_rate":      null,
#   "density_proxy":  null,
#   "window_start":   null,
#   "window_end":     null,
#   "computed_at":    "2026-03-15T12:45:30",
# }

class SegmentTrafficSummary(BaseModel):

    # ─── IDENTIFIER ─────────────────────────────────────────
    summary_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for this summary"
    )

    # ─── SEGMENT ────────────────────────────────────────────
    segment: str = Field(..., description="Road segment being summarized")

    # ─── TRAFFIC STATE ──────────────────────────────────────
    traffic_state: TrafficState = Field(
        ..., description="Classified traffic state: free / moderate / congested / severe"
    )

    # ─── COMPUTED INDICATORS ────────────────────────────────
    avg_speed:     float = Field(...,  description="Mean vehicle speed across signals in km/h")
    vehicle_count: int   = Field(...,  description="Total vehicles observed across signals")
    signal_count:  int   = Field(...,  description="Number of RSU signals used in this summary")

    # ─── STUB FIELDS ────────────────────────────────────────
    # These are defined now to establish the Firestore schema.
    # They will be populated once time-window aggregation and
    # segment metadata are implemented.

    flow_rate: Optional[float] = Field(
        None,
        description="[STUB] Vehicles per second within the window. "
                    "Requires fixed time window. Formula: vehicle_count / window_seconds."
    )
    density_proxy: Optional[float] = Field(
        None,
        description="[STUB] Vehicles per km of segment length. "
                    "Requires segment length metadata. Formula: vehicle_count / segment_length_km."
    )
    window_start: Optional[datetime] = Field(
        None,
        description="[STUB] Start of the aggregation time window. "
                    "Requires windowed aggregation pipeline."
    )
    window_end: Optional[datetime] = Field(
        None,
        description="[STUB] End of the aggregation time window. "
                    "Requires windowed aggregation pipeline."
    )

    # ─── TIMESTAMP ──────────────────────────────────────────
    computed_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Time when this summary was computed by the server"
    )


# ─── summary_to_dict() ───────────────────────────────────────
# Converts a SegmentTrafficSummary to a plain dictionary for Firestore.

def summary_to_dict(summary: SegmentTrafficSummary) -> dict:
    return {
        "summary_id":     summary.summary_id,
        "segment":        summary.segment,
        "traffic_state":  summary.traffic_state,
        "avg_speed":      summary.avg_speed,
        "vehicle_count":  summary.vehicle_count,
        "signal_count":   summary.signal_count,
        "flow_rate":      summary.flow_rate,
        "density_proxy":  summary.density_proxy,
        "window_start":   summary.window_start.isoformat() if summary.window_start else None,
        "window_end":     summary.window_end.isoformat() if summary.window_end else None,
        "computed_at":    summary.computed_at.isoformat(),
    }


# ─── AlertType ───────────────────────────────────────────────
# The reason category for generating an alert.
# Matches the Alert Type field in Table 4 of the GP1 report.
#
# congestion        — traffic state reached Congested or Severe
# abnormal_slowdown — sudden speed drop relative to baseline (future: baseline logic)
# suspected_incident — high density + very low speed pattern (future)
# state_transition  — traffic state worsened across consecutive windows (future)

AlertType = Literal[
    "congestion",
    "abnormal_slowdown",
    "suspected_incident",
    "state_transition",
]


# ─── SeverityLevel ───────────────────────────────────────────
# Severity of the alert based on how bad the condition is.
# Matches the Severity Level field in Table 4 of the GP1 report.
#
# low    — moderate traffic, informational only
# medium — congested, drivers should be aware
# high   — severe congestion or incident pattern

SeverityLevel = Literal["low", "medium", "high"]


# ─── AlertStatus ─────────────────────────────────────────────
# Lifecycle state of the alert.
# Matches the Status field in Table 4 of the GP1 report.
#
# active   — condition is ongoing
# resolved — condition returned to normal
# expired  — alert timed out without resolution confirmation

AlertStatus = Literal["active", "resolved", "expired"]


# ─── TriggerCondition ────────────────────────────────────────
# The specific rule that caused this alert to be generated.
# Matches the Trigger Condition field in Table 4 of the GP1 report.
#
# Current implementation uses threshold-based rules only.
# Future: persistence check, baseline deviation, state transition rules.

TriggerCondition = Literal[
    "speed_below_congested_threshold",   # avg speed < 40 km/h
    "speed_below_severe_threshold",      # avg speed < 20 km/h
    "baseline_deviation",                # future: speed dropped vs rolling baseline
    "persistence",                       # future: condition held for m consecutive windows
    "high_density_low_speed",            # future: density proxy + low speed combined
]


# ─── TrafficAlert ────────────────────────────────────────────
# Represents one alert generated by the server.
# Saved to the alerts collection in Firestore.
# Matches Table 4 (TrafficAlert Data Fields) from the GP1 report.
#
# Example document in Firestore:
# {
#   "alert_id":          "uuid",
#   "segment":           "Petra St",
#   "alert_type":        "congestion",
#   "severity":          "high",
#   "trigger_condition": "speed_below_severe_threshold",
#   "status":            "active",
#   "avg_speed":         15.3,
#   "total_vehicles":    42,
#   "signal_count":      10,
#   "traffic_status":    "severe",
#   "alert_message":     "Heavy traffic on Petra St - avg speed 15.3 km/h",
#   "generated_at":      "2026-03-15T12:45:30",
# }

class TrafficAlert(BaseModel):

    # ─── IDENTIFIERS ────────────────────────────────────────
    alert_id:  str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for this alert"
    )
    segment:   str = Field(..., description="Road segment affected")

    # ─── CLASSIFICATION ─────────────────────────────────────
    alert_type:        AlertType        = Field(..., description="Category of the alert")
    severity:          SeverityLevel    = Field(..., description="Severity level: low / medium / high")
    trigger_condition: TriggerCondition = Field(..., description="Rule that triggered this alert")
    status:            AlertStatus      = Field("active", description="Alert lifecycle status")

    # ─── TRAFFIC DATA AT TIME OF ALERT ──────────────────────
    # Snapshot of the traffic conditions that caused this alert.
    avg_speed:      float = Field(..., description="Average speed at time of alert in km/h")
    total_vehicles: int   = Field(..., description="Total vehicles observed across signals")
    signal_count:   int   = Field(..., description="Number of signals used in analysis")
    traffic_status: str   = Field(..., description="Traffic status: free / moderate / congested / severe")

    # ─── MESSAGE ────────────────────────────────────────────
    alert_message: str = Field(..., description="Human-readable alert description")

    # ─── TIMESTAMPS ─────────────────────────────────────────
    generated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Time when this alert was generated by the server"
    )
    resolved_at: Optional[datetime] = Field(
        None,
        description="Time when this alert was resolved. None if still active."
    )


# ─── alert_to_dict() ─────────────────────────────────────────
# Converts a TrafficAlert to a plain dictionary for Firestore.

def alert_to_dict(alert: TrafficAlert) -> dict:
    return {
        "alert_id":          alert.alert_id,
        "segment":           alert.segment,
        "alert_type":        alert.alert_type,
        "severity":          alert.severity,
        "trigger_condition": alert.trigger_condition,
        "status":            alert.status,
        "avg_speed":         alert.avg_speed,
        "total_vehicles":    alert.total_vehicles,
        "signal_count":      alert.signal_count,
        "traffic_status":    alert.traffic_status,
        "alert_message":     alert.alert_message,
        "generated_at":      alert.generated_at.isoformat(),
        "resolved_at":       alert.resolved_at.isoformat() if alert.resolved_at else None,
    }