// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv1nkgRVd47KYqoqISdYhRMK0vuZy9OUQ',
    appId: '1:794649373948:web:5832618438358780797b79',
    messagingSenderId: '794649373948',
    projectId: 'smartstreetintelligencesystem',
    authDomain: 'smartstreetintelligencesystem.firebaseapp.com',
    databaseURL: 'https://smartstreetintelligencesystem-default-rtdb.firebaseio.com',
    storageBucket: 'smartstreetintelligencesystem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb6qPso_juAtd3Wpjo59mNSmusiOFEEII',
    appId: '1:794649373948:android:bc9fa0de34436fa1797b79',
    messagingSenderId: '794649373948',
    projectId: 'smartstreetintelligencesystem',
    databaseURL: 'https://smartstreetintelligencesystem-default-rtdb.firebaseio.com',
    storageBucket: 'smartstreetintelligencesystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj3hexHkeKyiXZE0QNRiMFJ1fApyu_cfI',
    appId: '1:794649373948:ios:5c0c24f24af26007797b79',
    messagingSenderId: '794649373948',
    projectId: 'smartstreetintelligencesystem',
    databaseURL: 'https://smartstreetintelligencesystem-default-rtdb.firebaseio.com',
    storageBucket: 'smartstreetintelligencesystem.firebasestorage.app',
    iosBundleId: 'com.example.iscsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj3hexHkeKyiXZE0QNRiMFJ1fApyu_cfI',
    appId: '1:794649373948:ios:5c0c24f24af26007797b79',
    messagingSenderId: '794649373948',
    projectId: 'smartstreetintelligencesystem',
    databaseURL: 'https://smartstreetintelligencesystem-default-rtdb.firebaseio.com',
    storageBucket: 'smartstreetintelligencesystem.firebasestorage.app',
    iosBundleId: 'com.example.iscsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv1nkgRVd47KYqoqISdYhRMK0vuZy9OUQ',
    appId: '1:794649373948:web:7bc2e2900b6ca10e797b79',
    messagingSenderId: '794649373948',
    projectId: 'smartstreetintelligencesystem',
    authDomain: 'smartstreetintelligencesystem.firebaseapp.com',
    databaseURL: 'https://smartstreetintelligencesystem-default-rtdb.firebaseio.com',
    storageBucket: 'smartstreetintelligencesystem.firebasestorage.app',
  );
}
