// ============================================================
// Project:  Intelligent Street Communication System (ISCS)
// File:     lib/main.dart
// Author:   Raghad Shatnawi
// Last Modified: 9 May 2026
// Purpose:  Entry point of the Flutter application.
//           Initializes the native splash screen, Firebase,
//           and launches the root MaterialApp widget.
//           The splash screen stays visible until the
//           AuthController resolves auth state and calls
//           FlutterNativeSplash.remove().
// ============================================================

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';

import 'package:iscs_app/firebase_options.dart';
import 'package:iscs_app/features/authentication/auth_gate.dart';
import 'package:iscs_app/utils/theme/theme.dart';

Future<void> main() async {
  // Ensure Flutter engine is initialized before any plugin calls.
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();

  // Keep the splash screen visible until FlutterNativeSplash.remove()
  // is called by the AuthController after auth state resolves.
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);

  // Initialize Firebase with platform-specific config.
  // firebase_options.dart is generated by: flutterfire configure
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const App());
}

// ─── App ─────────────────────────────────────────────────────
// Root widget. Sets up MaterialApp with light/dark theming.
// AuthGate handles routing based on Firebase auth state.
class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,

      // Follows the device OS theme setting (light or dark)
      themeMode: ThemeMode.system,

      // Defined in lib/utils/theme/theme.dart
      theme: TAppTheme.lightTheme,
      darkTheme: TAppTheme.darkTheme,

      home: const AuthGate(),
    );
  }
}